spring.application.name=finpay-kafka-listener
server.port=${FINPAY_LISTENER_PORT:8081}

finpay.kafka.topic=${FINPAY_KAFKA_TOPIC:finpay.payment-events.v1}
finpay.kafka.consumer-group=${FINPAY_KAFKA_CONSUMER_GROUP:finpay-audit-v1}
finpay.kafka.concurrency=${FINPAY_KAFKA_CONCURRENCY:3}
finpay.kafka.dlt-topic=${FINPAY_KAFKA_DLT_TOPIC:finpay.payment-events.v1.DLT}
finpay.kafka.dlt-consumer-group=${FINPAY_KAFKA_DLT_CONSUMER_GROUP:finpay-audit-dlt-v1}
finpay.kafka.dlt-concurrency=${FINPAY_KAFKA_DLT_CONCURRENCY:1}
finpay.kafka.max-retries=${FINPAY_KAFKA_MAX_RETRIES:3}
finpay.kafka.retry-interval-ms=${FINPAY_KAFKA_RETRY_INTERVAL_MS:2000}

spring.kafka.bootstrap-servers=${FINPAY_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9094}
spring.kafka.consumer.group-id=${finpay.kafka.consumer-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.listener.ack-mode=record
spring.kafka.listener.missing-topics-fatal=true
spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://127.0.0.1:1434;databaseName=finpay_listener_db;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${FINPAY_DB_USERNAME:sa}
spring.datasource.password=${FINPAY_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.flyway.baseline-on-migrate=false
